### ISSUE TITLE
Dashboard crashes when language is not set in the Cohort

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2018-ZeeguuDashboard#164]
e.g. with this situation: ![screenshot 2018-05-29 14 16 07](https://user-images.githubusercontent.com/464519/40658898-f4e89f34-634c-11e8-945a-1e563ac11f31.png)

i get this: 

<img width="1231" alt="screenshot 2018-05-29 14 02 39" src="https://user-images.githubusercontent.com/464519/40658909-fcd9526a-634c-11e8-9430-8b2769eaa044.png">

**Comment by Oli26** [comment]
I think this is an issue because when we load a cohort, we pull the data for that cohort from the database and then try to send that data to the dashboard in json form. I think a class not having a language id will cause this to crash. I'm not sure there is a way around this, perhaps another database updater to set all language_id codes?

**Comment by mircealungu** [comment]
Hmm. For now I've updated the language codes manually in my DB so there's no more NULL language in a cohort.

**Comment by mircealungu** [comment]
One possible solution would be to make the web show None when there is no language instead of simply crashing...

**Comment by Oli26** [comment]
Fixed :)
